
# Intermediate SQL

You now have a good knowledge of basic SQL, and you are able to create subsets, aggregations and new combinations of data. This is already enough to make good use of any database you have access to, allowing you leverage the database's data crunching abilities to extract results much more tailored to your needs than simply copying the entire table from Oracle to R.

## Create conditional statements with `CASE WHEN`

SQL is not made for traditional programming with looping, conditional operations, and variable assignments i the fast and loose way that we might be used to from other languages. SQL is operations on datasets, but there is a syntax for if-else statements that comes in handy: `CASE WHEN`.

We noted earlier that some of the sales in our transaction data seems to be negative - which is unexpected. In real world data, surprises like this are common, and often come about because you lack knowledge of where the data comes from. Indeed, if you have experience from sales, you might be bored right now thinking *of course some reciepts are negative! Have you never heard of a return?*

Let's explore the negative values a little more. Since it was the product of `unitPrice` and `Quantity` that was negative, we are looking for rows where either one of them is negative (but strictly speaking it would be OK if both of them were). As so often, we start by just looking at a few examples to get a feel for what we are dealing with.


```{sql connection=con}
SELECT * FROM trx
WHERE unitprice<0 OR quantity<0
FETCH FIRST 10 ROWS ONLY
```

Immediately, we notice that these are often quite normal-sounding products, and the quantity is negative, not the price. Let's check that theory.

```{sql connection=con}
SELECT * FROM trx
WHERE unitprice<0
FETCH FIRST 10 ROWS ONLY
```

Out of over 500 000 rows, 2 have a negative unit price because they seem to be striking bad debt that they can't collect.

Now, we can use the `CASE WHEN` clause to find the total effect of these negative values.

```{sql connection=con}
SELECT SUM(CASE WHEN quantity>0 AND unitPrice>0 THEN quantity*unitPrice ELSE NULL END) AS positive_sales, 
  SUM(quantity*unitPrice) AS all_sales 
FROM trx
```

Had the shop been able to stave off bad debt and the negative quantities that we for now presume to be returns, it would have 10 million pounds in revenue. The difference, close to 900 000 ponds, is about 10 % of sales. In order to find out if this is to be expected, we would need to talk to someone with knowledge of the business.

From a technical standpoint, the SQL sums either the product of quantity and unitPrice if they are both positive, or NULL (which the sum function implicitly omits) if one or both of them is negative. This gives us the sum of positive sales right next to the sum of all sales. Thanks to `CASE WHEN` there was no need to split this into two queries. 
In R, aggregation functions usually return NA (the R version of NULL) by default if one or more values it is aggregating is NA. SQL simply omits missing values, pretending they aren't even there.


|Other Databases|
|--------------------------------------|
|Oracle requires any group by variables to be included in the select statement too. Some other databases do not require this. Likewise, the group by statement can not include the shortnames assigned to the variables|


## Filter on aggregates with `HAVING`

When we found the 4 biggest countries, we used the `rownum` keyword in combination with `ORDER BY` to get the 4 biggest countries. 4 was an arbitrary cutoff, maybe we are interested in all countries with more than 100 000 pounds in total sales? The `WHERE` clause only works on the underlying rows, not on computed aggregates. Instead, there is a seperate keyword, `HAVING`, that lets you filter on the aggregated values. Let's find the countries with more than 100 000 in revenue.

```{sql connection=con, eval=FALSE}
SELECT country, SUM(quantity*unitPrice) AS sales FROM trx
GROUP BY country
HAVING SUM(quantity*unitPrice)>100000
ORDER BY 2 desc
```

There is a total of 6 contries that sold for mor than 100 000 pounds, with Australia closest to the cutoff with 137 000 in sales. Unfortunately, `HAVING` doesn't understand the column names we assign in `SELECT` (`sales` in this case), so we need to repeat the entire expression when filtering. `ORDER BY`, on the other hand, is perfectly happy sorting by either `sales` or simply the column number as shown here. 


## Limiting your result with `FETCH FIRST`
If you have a big table and you just want to limit the number of results returned from a query, there is an option besides using the `ROWNUM` pseudo-column. And even though rownum works great for many purposes, it fails if you want to see result 100-199. There is no good way to exclude row 1-99 from the output using rownum. A better, and more tidy alternative, is to use a special clause to limit the resultset. Reusing the code showing the biggest countries, we can select the 10 biggest countries.

```{sql connection=con}
SELECT country, SUM(quantity*unitPrice) AS sales FROM trx
GROUP BY country
ORDER BY sales desc
FETCH FIRST 10 ROWS ONLY
```

This limits the resultset in much the same way as the `ROWNUM` clause, but it is easier to parse visually because it is distinct from the where-statement, and it is possible to expand this clause in ways not possible with `ROWNUM`. Take the classical example of cycling through a paginated list of items. You have a large number of rows, ordered by some condition, and you want to show only 10 at a time, with a "next page" link at the bottom of the list. If we want to show rows 11-20 from the movie table, we can simply modify the query slightly.

```{sql connection=con}
SELECT country, SUM(quantity*unitPrice) AS sales FROM trx
GROUP BY country
ORDER BY sales desc
OFFSET 10 ROWS FETCH NEXT 10 ROWS ONLY
```


## Simple convenience functions

### The `decode` function
Sometimes, a `CASE WHEN` statement can be a little much. Enter the `decode` function, which is a type of case-when statement as a function. The `decode` function takes an even number of arguments. The first value is the variable or expression you want to check. The second and the third are the value you are checking against and the value you want returned, respectively. This argument pair can be repeated any number of times. Lastly, there is a single argument to specify the *else* value, which is returned if none of the previously stated happen.

Say, you want to quickly recode the `gender` from 'Male' and 'Female' to the german equivalents. This can be done as follows:

```{sql, connection=con}
SELECT DECODE(gender, 'Male', 'Männlich', 'Weiblich') FROM customer
```

If we want to take care of potential missing/bad values in the data, we have to add an *unknown* category. If we don't, all values not equal to 'Male' will return with the *female* label. At the same time, lets use what we have learned about aggregations and unions to check that the result is correct (and learn something about the gender balance among our customers).

```{sql, connection=con}
SELECT DECODE(gender, 'Male', 'Männlich', 'Female', 'Weiblich', 'Nicht spezifiziert') AS geschlecht, COUNT(1) AS anzahl FROM (
SELECT gender FROM customer
UNION ALL
SELECT NULL AS gender FROM dual
)
GROUP BY DECODE(gender, 'Male', 'Männlich', 'Female', 'Weiblich', 'Nicht spezifiziert')
ORDER BY 2 DESC
```

The `NULL` value triggers the *other* part of the decode function, and results in one extra row and one entry in the "unspecified" category.

### upper / lower

In many search and language processing applications it is vital to omit differences in capitalization. The fastest way to do this is usually to convert everything to upper- or lowercase, which can be done easily in SQL with the UPPER() and LOWER() function.

These functions are quite uncomplicated. The short example below converts email-addresses to both upper and lower case.

```{sql, connection=con}
SELECT email, UPPER(email), LOWER(email) FROM customer
FETCH FIRST 5 ROWS ONLY
```

### substring
Text strings are often very well-structured, and you may know exactly which characters in the column you are interested in. The `SUBSTR` function takes two (optionally three) arguments. First, the column you want to find a substring in. Second, the letter number you want to start reading from, and optionally the number of letters you want to return.

In the `customer` table, the `INCOME_LEVEL` column consists of a letter, followed by the actual income bracket. Suppose we want to return only the letter in our query, or only the income level, the `SUBSTR` function is fast and easy because we always know which position the letters and dollar amounts have.

```{sql, connection=con}
SELECT gender, SUBSTR(income_level, 1,1), SUBSTR(income_level, 4) FROM customer
FETCH FIRST 5 ROWS ONLY
```

### Regular expressions

Making sense of freeform text is always a challenge, and regular expressions (or regex in jargon) is a powerful tool for the task. Regex is a way too complex subject to explain in detail here, but we do afford ourselves a few examples from Oracle's regex functions.

In short, regex allows you to find patterns in text, such as extracting only digits from a field, validating email addresses, or select all capitalized words that occur in groups of two or more (suspected personal names).

```{sql, connection=con}
SELECT COUNT(*) FROM customer
WHERE REGEXP_LIKE(email, '[a-zA-Z0-9_\.]+@[a-zA-Z0-9_\.]+\.[a-zA-Z]')
```

### Dealing with dates and times

## What we are not going to cover

### PL/SQL

`PL/SQL` is Oracle's programming language extension to SQL. It lets you declare variables, run conditional statements and loops, in order to generate SQL statements on the fly.

Since we are using R which has all these features, there are few arguments for learning PL/SQL too.

### the `dbplyr` library

If you prefer avoid SQL when possible, you should consider using a library called `dbplyr`. This is an interface that lets you write familiar R code, that is then run in the database as SQL. The authors have done a great job at optimizing the code, so that the resulting database queries are every bit as performant as you could hope for.

